### ISSUE TITLE
forum pics

### ISSUE THREAD

**Issue by kevinmckay1** [jamesmonek/maineflyfishpublic#12]
I have been seeing more and more people saying they can't upload pics

**Comment by jamesmonek** [comment]
Fixed permissions issues for the upload directory. Also increase upload size. This will impact backup, storage and costs.

**Comment by kevinmckay1** [comment]
Didnt need to increase upload size it was just no one could upload any picsI resized and still wouldn't work


Sent from my  U.S.Cellular© Smartphone
-------- Original message --------From: James Monek <notifications@github.com> Date: 6/10/18  11:59 AM  (GMT-05:00) To: jamesmonek/maineflyfishpublic <maineflyfishpublic@noreply.github.com> Cc: kevinmckay1 <admin@maineflyfish.com>, Author <author@noreply.github.com> Subject: Re: [jamesmonek/maineflyfishpublic] forum pics (#12) 
Fixed permissions issues for the upload directory. Also increase upload size. This will impact backup, storage and costs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/jamesmonek/maineflyfishpublic/issues/12#issuecomment-396060172","url":"https://github.com/jamesmonek/maineflyfishpublic/issues/12#issuecomment-396060172","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jamesmonek/maineflyfishpublic","title":"jamesmonek/maineflyfishpublic","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jamesmonek/maineflyfishpublic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jamesmonek in #12: Fixed permissions issues for the upload directory. Also increase upload size. This will impact backup, storage and costs."}],"action":{"name":"View Issue","url":"https://github.com/jamesmonek/maineflyfishpublic/issues/12#issuecomment-396060172"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [jamesmonek/maineflyfishpublic] forum pics (#12)",
"sections": [
{
"text": "",
"activityTitle": "**James Monek**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@jamesmonek",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"jamesmonek/maineflyfishpublic\",\n\"issueId\": 12,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/jamesmonek/maineflyfishpublic/issues/12#issuecomment-396060172"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 342497603\n}"
}
],
"themeColor": "26292E"
}
